### PR TITLE
Forms: typos/grammar issues

### PR DESCRIPTION
**Pull request by filiphlm**
Needs more work, but let's call it a start…

### CODE REVIEW

**Comment by f3l1x** [comment]
Oh, thanks. Does it solve any issue or it's new one?

**Comment by filiphlm** [comment]
It’s a new one (unless I’m mistaken).


On 28 June 2017 at 14:40:18, Milan Felix Šulc (notifications@github.com)
wrote:

Oh, thanks. Does it solve any issue or it's new one?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nette/docs/pull/546#issuecomment-311647647>, or mute
the thread

**Comment by filiphlm** [comment]
Sorry — there's (much) more. I'm on it.

**Comment by f3l1x** [comment]
@filiphlm Ok, let me know.

**Comment by filiphlm** [comment]
@f3l1x OK, let's call it a day. TM: Still „needs more work“, but I'm done with this PR. (?)

**Comment by dg** [comment]
Unbeleivable hov many misstakes there where :)

Thanks

**Comment by f3l1x** [comment]
Good job by the way ;-)

**Comment by filiphlm** [comment]
De nada. My pleasure ,-)

**Comment by f3l1x** [comment]
@filiphlm Can't wait for the next PR. :eyes:

**Pull request merged**
