### PR TITLE
configuring: Sync intro links with heading texts

### PR DESCRIPTION
**Pull request by jtojnar**
This fixes a few broken links.

I wonder if we should not have some broken link checker running in CI.

### CODE REVIEW

**Comment by dg** [comment]
Thanks

**Comment by jtojnar** [comment]
@dg Is the build script for the website available somewhere? The simplest solution might be running it in CI here followed up by a standard link checker.

**Comment by dg** [comment]
The builder script is not able to check this.

**Comment by jtojnar** [comment]
For starters, we do not need the build script to handle that – we just need the HTML files and some other tool can handle the checking, e.g. https://packagist.org/packages/dantleech/fink

**Pull request merged**
