### PR TITLE
fixed creating Latte templates in mailing

### PR DESCRIPTION
**Pull request by petrparolek**
- bug fix

obrazek

### CODE REVIEW

**Comment by mabar** [comment]
Seems to be working perfectly fine with nette/application v3.1.7 and nette/di v3.0.13

Issue is probably somewhere else.

image
image

**Comment by petrparolek** [comment]
could you test latest nette/application please?

**Comment by mabar** [comment]
Not really. But it is this line, causing your issues https://github.com/nette/application/blob/44e8c2d9ecec10241be663cae13b7be3c26e6a33/src/Bridges/ApplicationDI/LatteExtension.php#L72 It limits autowiring to `ITemplateFactory` (and any of its aliases)

**Comment by dg** [comment]
Thanks.

(A nechovej se jako píčus, viz Slack)

**Pull request merged**
