### PR TITLE
Fix postFormSucceeded example

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by dg** [comment]
The $form parameter is optional.

**Comment by lulco** [comment]
OK, my bad, I use nette/forms: "~3.0.7". I didn't know it is optional now... but than it should be consistent in docs and don't use it if not needed.

**Comment by dg** [comment]
I agree. And did you find it inconsistent anywhere?

**Comment by lulco** [comment]
no, just here in https://doc.nette.org/cs/3.1/quickstart/creating-posts (and en version)

create new post:
```
public function postFormSucceeded(array $values): void
```

edit existing post:
```
public function postFormSucceeded(Form $form, array $values): void
```

None of them needs Form, so they should be the same.
```
public function postFormSucceeded(array $values): void
```

**Pull request closed without merging**
