### PR TITLE
Latte: add info about "breaklines" filter

### PR DESCRIPTION
**Pull request by matyx**

### CODE REVIEW

**Comment by dg** [comment]
`alias pro `|escape|nl2br|noescape` is not descriptive.

**Comment by matyx** [comment]
What description do you suggest? Imo it is good for experienced nette devs (better than "escape, replace newlines with <br> and print unescaped"), but I understand it may be confusing for newcomer.

**Comment by dg** [comment]
Something like `Inserts HTML line breaks before all newlines in a string`

**Comment by matyx** [comment]
I've updated czech version only - added article about newlines (`Inserts HTML line breaks before all newlines` is imo confusing with nl2br). Can you please take a look @dg? I'll translate it to english too, if it seems okay to you. Or the second thought was to remove nl2br, due its deprecation since latte 2.4?

**Comment by dg** [comment]
Thanks! I agree to remove nl2br in 2.4 doc, it will make it more clearly.

**Comment by dg** [comment]
Thanks!

**Comment by matyx** [comment]
Thanks too, for coop and for merging.

**Pull request merged**
