### PR TITLE
Quickstart: Added use statement for Forms

### PR DESCRIPTION
**Pull request by MachMartin**
Added "use" when mentioning Form for the first time (may be confusing for begginers).

### CODE REVIEW

**Comment by matej21** [comment]
it is already here https://doc.nette.org/en/2.4/quickstart/single-post

**Comment by MachMartin** [comment]
I've noticed but that can be easily missed - especially if the user/begginner doesn't just copy&paste but writes the code by himself (and since there are no forms on that page, that's quite probable). 

I think it's better this way - or at least add some note/footnote below that.

**Comment by dg** [comment]
or what about comment after `new Form` ?

**Comment by MachMartin** [comment]
I guess a comment would be enough. My point is that devs without IDE will have to look it up (at least on the previous page - single post). IDE will tell you more variants (`Application\UI\Forms`, `Forms\Forms` and maybe a few more).

**Pull request closed without merging**
