### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by dragomano**
* Base chapters
* Quickstart
* Application
* Best practices
* Contributing
* Caching
* Forms
* Dependency Injection
* Database
* PHP Code Generator

### CODE REVIEW

**Comment by dg** [comment]
WOW!

**Comment by dragomano** [comment]
> WOW!

Does it mean I can continue? :)

**Comment by dg** [comment]
There is a little complication for me. I'm improving the documentation a lot and I'm doing every edit in English and Czech at the same time. But I can't do it in Russian. So over time the Russian version will become unupdated. 




I don't know how to handle this…

**Comment by dragomano** [comment]
I try to update my own translations whenever possible. For example, from the 2020 year, I support translation for [Grav CMS.](https://github.com/dragomano/Grav-Learn-Ru)

**Comment by mabar** [comment]
I was thinking about some translation service which would with every push to english version create one task per language to update other versions, with link to the diff included, . But no idea if something like this exists or if it's worth it.

**Comment by dragomano** [comment]
I can recommend Crowdin for it.

**Comment by dg** [comment]
My plan now is to completely rewrite the intro pages of Nette, Latte, Tester, etc (yes, unfortunately even the base chapter you translated) and gradually add information about the new release Nette 4. Then I think the changes will be rather few.

**Comment by dragomano** [comment]
> My plan now is to completely rewrite the intro pages of Nette, Latte, Tester, etc (yes, unfortunately even the base chapter you translated) and gradually add information about the new release Nette 4. Then I think the changes will be rather few.

Switching to Crowdin will enable translators to work with you at the same time.

**Comment by dg** [comment]
So I'm afraid the Russian translation will be pointless because Putin plans to disconnect and isolate Russia from the world internet. I'm sorry how the situation has escalated, this should never have happened.

**Comment by ivanscm** [comment]
I've been using Nette in development for a long time (since version 2), I have a great desire to get involved in translation. In spite of the situation, I propose not to stop the work.

**Comment by petrparolek** [comment]
I think we should close this PR.

**Comment by petrparolek** [comment]
Add Esperanto is better solution.

**Comment by dragomano** [comment]
https://doc.nette.org/en/contributing/documentation
> Contributing to the documentation is one of the many ways you can help Nette. It is also one of the most rewarding activities, as you help others understand the framework.

**Comment by dg** [comment]
Thanks, merged!

I'm reworking the documentation structure now, but it should be up on the web in a while.

**Pull request closed without merging**
