### PR TITLE
Added npm import integration (en)

### PR DESCRIPTION
**Pull request by dakur**

### CODE REVIEW

**Comment by dakur** [comment]
Not sure that this is the best way to do it, but did not found any better.

**Comment by dakur** [comment]
Maybe even better would be link it from `vendor` to keep client lib synced with backend version. Question is why there even is a package on npm then?

**Comment by dakur** [comment]
We've just discussed in our company that in case of linking it from `vendor`, our CI build time would increase of 20 seconds which is too big cost for having not-in-sync a library which is changing so rarely. Thus linking script from `npm` is good compromise.

So maybe we could mention all three possibilities in docs - npm, vendor and local file. We can possibly cdn (nette.github.io) option as well. What do you mean @dg?

**Comment by dg** [comment]
I agree!

**Comment by dakur** [comment]
Closed in favor of #823

**Comment by dg** [comment]
Nezakládej prosím s každou úpravou nový PR, ale forcepusni do toho starého.

**Comment by dakur** [comment]
> Nezakládej prosím s každou úpravou nový PR, ale forcepusni do toho starého.

Předtím jsem editoval všechno jen tady na githubu, ale teď už jsem sáhl po editoru a git clone, tak jsem to chtěl udělat v jednoho PR.

**Pull request closed without merging**
