### PR TITLE
Repaired bugs and added new features in convertor

### PR DESCRIPTION
**Pull request by MichalKalita**
Repaired several bugs
- Images had wrong addresses
- Links between documentation pages doesn't work
- Design trouble

New features
- In header is added links to homepage and language switch
- Link to API is linked to same version as documentation version (checked from git branch name)

### CODE REVIEW

**Comment by f3l1x** [comment]
ping @dg

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by dg** [comment]
Convertor is just an example that is not actually used to generate documentation. I have not studied this PR yet.

**Comment by TomasVotruba** [comment]
@dg I see. Is this tool open-sourced somewhere? 
Should be PR resend there?

In any case, this can be closed then.

**Comment by dg** [comment]
It is open sourced here :)

**Comment by TomasVotruba** [comment]
So what file is the correct one if not Convertor.php?

**Comment by dg** [comment]
This tool is just example. Real website is generated in a different way, source codes of web site will never be open sourced. If there is bug on website, tell me and I will fix it.

**Comment by TomasVotruba** [comment]
I see.

This PR can be closed then.

@Myiyk Could you please reopen those bugs as 3 standalone issue with more detailed report, what exactly is wrong?

**Comment by Myiyk** [comment]
I know this is not backend of doc.nette.org
This is only "simulator" of documentation. But it has some bugs, so I try fix it.

I didn't found any bug in doc.nette.org

**Pull request closed without merging**
