### PR TITLE
add description for nette.inject in SearchExtension

### PR DESCRIPTION
**Pull request by dakorpar**
Took me some time to get to that info and it's kinda basic info that a lot of people want to know

### CODE REVIEW

**Comment by dg** [comment]
Yeah, but I really don't want anyone to know it and use it :-)

**Comment by mabar** [comment]
Understandable in presenters, which have many dependencies by-design, it's better to use constructor everywhere else.

**Comment by dakorpar** [comment]
Well I'm using it only in abstract classes, otherwise it's a big no, but still it's worth noting.
Maybe better would be then to just add decorator for those abstract classes

**Comment by dg** [comment]
Of course this should be in the documentation, but it belongs to the InjectExtension documentation. This should not be in the SearchExtension configuration description because for the vast majority of users this is irrelevant.

**Comment by dakorpar** [comment]
In programming and logic way I agree, but most of developers will look into search extension documentation to see how to do that...
However I agree and I'm closing this.

**Pull request closed without merging**
