### PR TITLE
bump required php version to 7.1.0

### PR DESCRIPTION
**Pull request by rolandtoth**
In the docs it's still 5.6.0, and getting this error on 7.0 for protected const:

`syntax error, unexpected 'const' (T_CONST)...`

### CODE REVIEW

**Comment by dg** [comment]
Please use the last stable release, it is compatible with 5.6

**Comment by rolandtoth** [comment]
Thanks, but which one is the stable version? 1.x?

I've downloaded the master here on GitHub (zipped), and the readme says `Nette Tester requires PHP 7.1 and supports PHP up to 7.2.`. In the `Frameworks\Environment.php` there's `public const` which requires PHP 7.1. So it's not clear I think.

**Comment by dg** [comment]
https://github.com/nette/tester/releases

**Comment by rolandtoth** [comment]
Thanks. How about adding a note that 5.6 is for the stable release? (see my latest commit)

**Comment by milo** [comment]
I created an overview of supported PHP versions https://github.com/nette/docs/commit/640790161af25768ca304b23b2d8621a9ea1dd6f

**Comment by rolandtoth** [comment]
Great, thanks!

**Pull request closed without merging**
