### PR TITLE
Edited link

### PR DESCRIPTION
**Pull request by Machy8**
- Link was pointing to a nonexisting page - https://api.nette.org/2.3/Nette.DI.Extensions.NetteExtension.html#_afterCompile

### CODE REVIEW

**Comment by Myiyk** [comment]
You have to edit code on line 162, because code on link is not same as code in documentation.

**Comment by Machy8** [comment]
Yes, you are right. I know. But I have no idea which part of the code according to the "Here is a piece of code of initialize where Nette..." is the right part. But if it doesn't matter, I can copy there the whole code (but perhaps that is not what authors wanted).

**Comment by dg** [comment]
IMHO link should be removed, NetteExtension doesn't exist now.

**Comment by Machy8** [comment]
So, should I edit the pull request in some way?

**Comment by dg** [comment]
Yes, you can remove link and push it again.

**Comment by f3l1x** [comment]
It needs rebase.

**Pull request merged**
